import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Molecules/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Silvia Melia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons8-vespa-32.png" />
      </Head>
      <Hero />
    </>
  );
}
