import Head from "next/head";
import Hero from "@/components/Molecules/Hero/Hero";
import About from "@/components/Molecules/About/About";
import Experience from "@/components/Molecules/Experience/Experience";
import Projects from "@/components/Molecules/Projects/Projects";
import BackToTop from "@/components/Atoms/BackToTop/BackToTop";

export default function Home() {
  return (
    <>
      <Head>
        <title>Silvia Melia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons8-vespa-32.png" />
      </Head>
      <Hero />
      <About />
      <Projects />
      <Experience />
      <BackToTop />
    </>
  );
}
